version : '3'

services:
  app :
    container_name: numerical-final
    build: .
    port:
      - '80:3000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: testmongo
    ports:
      - '27017:27017'